title: Laihz
description: noting is written
show_downloads: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://lhz1165.github.io" # change this to the base hostname & protocol for your site


google_analytics:


# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Laihz
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri

plugins:
  - jekyll-target-blank
  - jekyll-paginate
target-blank:
    rel: nofollow

header_page_refs: ['now','contact', 'class']
paginate: 10
paginate_path: "/page:num/"

